/**
 * Database consisting of the correct IPA pronunciations for mis-pronounced words by the AI
 */
const IPA_PRONUNCIATIONS = {
    clave: "klɛ́jv",
    herb: "hɜːrb",
    Laban: "laˈban",
    Keturah: "keɪˈtʊra",
    Medan: "miˈdan",
    Dedan: "deɪˈdæn",
    Sheba: "ʃeɪˈbɑ",
    Leummim: "leɪˈuːmɪm",
    Hanoch: "χaˈnɔx",
    Mamre: "ˈmʌmri",
    Lahairoi: "leɪˌhaɪˈrɔɪ",
    Jetur: "dʒərtʊr",
    Naphish: "neɪfɪʃ",
    Kedemah: "kiːˈdɛmɑː",
    sware: "swɛər",
    Padanaram: "padanaram",
    "Padan-aram": "padanaram",
    Leban: "laˈban",
    Rehoboth: "riˈhoːβoθ",
    Ahuzzath: "ʔaˈħuzatχ",
    Phichol: "ˈfaɪˌkɔl",
    Beeri: "biːˈraɪ",
    Bashemath: "baʃemɑθ",
    badest: "ˈbeɪdɪst",
    Hazezontamar: "hazɛzɔntaˈmaʁ",
    Chedorlaomer: "kɪdohˈlɑɑhohma",
    Shaveh: "ʃɛɪˈva",
    Aner: "ɑˈnɛʁ",
    Eliezer: "ɛliˈʕɛzɛr",
    Ur: "ʔur",
    Dan: "Dan",
    Kenizzites: "kɛnɪˈzaɪts",
    Rephaims: "ˈrɛfəˌɪmz",
    Beerlahairoi: "bɛərlɑːˈhaɪ.rɔɪ",
    Ammon: "ˈæhmən",
    Emins: "ˈiːmɪmz",
    Birsha: "ˈbɪrʃə",
    Elam: "ˈeːləm",
    Haran: "ˈhærɑn",
    "Nahor's": "ˈneɪhɔrz",
    Nahor: "ˈneɪhɔːr",
    Machpelah: "maːxˈpɛlɑː",
    Mahalath: "meɪˈhəlæθ",
    Nebajoth: "nɛbˈeɪˌdʒoθ",
    Naphtali: "næfˈteli",
    Gad: "ɡad",
    Hanoch: 'heɪˈnɑx',
    Phallu: "ˈfælu",
    Simeon: "ˈsɪmiən",
    Jemuel: "dʒɛmjuːɛl",
    Jamin: "dʒamɪn",
    Jachin: "ˈdʒahɪn",
    Shaul: "ʃeɪɔːl",
    Gershon: "ˈɡɜrʃen",
    Onan: "ˈoʊnən",
    Shelah: "ˈʃiːlə",
    Zerah: "ˈzɛrə",
    Hamul: "ˈhɑːmul",
    Phuvah: "ˈfuːvə",
    Job: "dʒoʊb",
    Sered: "ˈsɛrɛd",
    Elon: "ˈɛlɑn",
    Jahleel: "ˈdʒɑːliːl",
    Ziphion: "ˈzɪfiən",
    Haggi: "hɑɡaɪ",
    Shuni: "ˈʃuːni",
    Ezbon: "ˈɛzˌbɑn",
    Eri: "ˈɛraɪ",
    Arodi: "ˈɑːroʊdi",
    Areli: "ˈɑːrelaɪ",
    Asher: "ˈaʃər",
    Isui: "ˈiːsuːi",
    Beriah: "bɛˈraɪə",
    Serah: "ˈsɛrə",
    straitly: "ˈstreɪtli",
    Belah: "bɛˈlɑː",
    Becher: "biːxkər",
    Gera: "ˈɡɛrə",
    Naaman: "ˈneːɑːmɑ:n",
    Ehi: "iːhaɪ",
    Rosh: "rəʊʃ",
    Muppim: "ˈmupɪm",
    Huppim: "ˈhupɪm"
}

module.exports = {
    IPA_PRONUNCIATIONS
}